version: '3'

services:
  api:
      build:
        context: .
        dockerfile: docker/api/Dockerfile
      volumes:
        - ./api:/usr/src/app
        - ./web/build:/usr/src/web/build
        - /usr/src/app/node_modules
      ports:
        - 3001:3000
        - 9229:9229
      env_file:
        - .env  
      links:
        - mongo
      command: npm run debug  
  mongo:
      image: 'bitnami/mongodb:4.1'
      ports:
        - "27017:27017"
      env_file:
        - .env        
      volumes:
        - 'mongo-data:/bitnami'
        - './api/queries/index.js:/queries.js'
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: pass
volumes:
  mongo-data:
